// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_API_KEY',
    appId: 'YOUR_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'nebras-9118c',
    authDomain: 'nebras-9118c.firebaseapp.com',
    databaseURL: 'https://nebras-9118c-default-rtdb.firebaseio.com',
    storageBucket: 'nebras-9118c.firebasestorage.app',
    measurementId: 'G-8JXFD4GCLY',
  );

  // ── macOS / iOS ─────────────────────────────────────────────────────
  // bundle id محدَّث إلى `com.nebras.mobile` ليطابق project.pbxproj.
  // ⚠️ ملاحظة لتطوير iOS لاحقاً: يجب تسجيل تطبيق iOS الجديد في Firebase
  // Console بهذا الـ bundle id ثمّ استبدال `appId` و `apiKey` بالقيم من
  // GoogleService-Info.plist المُولَّد. النشر على Play Store (Android)
  // لا يتأثر بهذه القيم.
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_API_KEY',
    appId: 'YOUR_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'nebras-9118c',
    databaseURL: 'https://nebras-9118c-default-rtdb.firebaseio.com',
    storageBucket: 'nebras-9118c.firebasestorage.app',
    iosBundleId: 'com.nebras.mobile',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_API_KEY',
    appId: 'YOUR_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'nebras-9118c',
    databaseURL: 'https://nebras-9118c-default-rtdb.firebaseio.com',
    storageBucket: 'nebras-9118c.firebasestorage.app',
    iosBundleId: 'com.nebras.mobile',
  );

  // ── Android — تطبيق com.nebras.mobile (الجديد) ─────────────────────
  // الـ appId مأخوذ من android/app/google-services.json (المدخل الثاني
  // في `client[]`). يجب أن يطابق `mobilesdk_app_id` وإلّا تفشل التحليلات
  // و App Check.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_API_KEY',
    appId: 'YOUR_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'nebras-9118c',
    databaseURL: 'https://nebras-9118c-default-rtdb.firebaseio.com',
    storageBucket: 'nebras-9118c.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR_API_KEY',
    appId: 'YOUR_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'nebras-9118c',
    authDomain: 'nebras-9118c.firebaseapp.com',
    databaseURL: 'https://nebras-9118c-default-rtdb.firebaseio.com',
    storageBucket: 'nebras-9118c.firebasestorage.app',
    measurementId: 'G-NGETP989SS',
  );

}